<script setup>
import { ref,computed,onUnmounted } from 'vue'
import { ArrowUp,ArrowDown,ArrowLeft,ArrowRight,Play,Pause,RotateCcw } from '@lucide/vue'
import { SIZE,initialState,step,opposite } from './engine.js'
const state=ref(initialState()),board=ref(null)
let timer,queue=[]
const caption=computed(()=>({ready:'Prêt à jouer ?',paused:'En pause',over:'Partie terminée',won:'Grille complétée !',running:'En jeu'})[state.value.status])
function start(){if(['over','won'].includes(state.value.status)){state.value=initialState();queue=[];}state.value.status='running';clearInterval(timer);timer=setInterval(()=>{state.value=step(state.value,queue.shift()||state.value.direction);if(state.value.status!=='running')clearInterval(timer)},140);board.value?.focus({preventScroll:true})}
function pause(){if(state.value.status==='running'){clearInterval(timer);state.value.status='paused'}else if(state.value.status==='paused')start()}
function reset(){clearInterval(timer);queue=[];state.value=initialState()}
function direct(dir){if(state.value.status!=='running'||queue.length>=2)return;const last=queue.at(-1)||state.value.direction;if(dir!==last&&!opposite(last,dir))queue.push(dir)}
function keyboard(e){if(['INPUT','SELECT','TEXTAREA','BUTTON','A'].includes(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;const dir={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',z:'up',w:'up',q:'left',a:'left',s:'down',d:'right'}[e.key];if(dir){e.preventDefault();direct(dir)}else if(e.code==='Space'){e.preventDefault();if(!e.repeat){if(state.value.status==='ready')start();else pause()}}}
function visibility(){if(document.hidden&&state.value.status==='running')pause()}
window.addEventListener('keydown',keyboard);document.addEventListener('visibilitychange',visibility)
onUnmounted(()=>{clearInterval(timer);window.removeEventListener('keydown',keyboard);document.removeEventListener('visibilitychange',visibility)})
</script>
<template><div class="game-ui"><header class="game-header"><span class="eyebrow">ARCADE / CLAVIER ET TACTILE</span><h1>Snake</h1><p>Attrape les fruits. Évite les murs et ta propre queue.</p></header><section class="settings"><div class="snake-score">Score <strong>{{ state.score }}</strong></div><button v-if="['running','paused'].includes(state.status)" @click="pause"><component :is="state.status==='running'?Pause:Play"/> {{ state.status==='running'?'Pause':'Reprendre' }}</button><button class="secondary" @click="reset"><RotateCcw/> Recommencer</button></section><div ref="board" class="snake-board" tabindex="0" aria-label="Terrain de Snake. Flèches ou ZQSD pour diriger, Espace pour mettre en pause."><svg :viewBox="`0 0 ${SIZE} ${SIZE}`" aria-hidden="true"><defs><pattern id="snake-grid" width="1" height="1" patternUnits="userSpaceOnUse"><path d="M 1 0 L 0 0 0 1" fill="none" stroke="#304034" stroke-width=".025"/></pattern></defs><rect width="20" height="20" fill="url(#snake-grid)"/><rect v-for="(part,i) in state.snake" :key="i" :x="part.x+.07" :y="part.y+.07" width=".86" height=".86" rx=".12" :fill="i===0?'#b9ffe0':'#70c79f'"/><circle v-if="state.food" :cx="state.food.x+.5" :cy="state.food.y+.5" r=".34" fill="#ef9b70"/></svg><div v-if="state.status!=='running'" class="snake-overlay"><strong>{{ caption }}</strong><p v-if="state.status==='over'||state.status==='won'">{{ state.score }} points</p><button @click="start"><Play/> {{ state.status==='paused'?'Reprendre':state.status==='ready'?'Jouer':'Rejouer' }}</button></div></div><p class="snake-instructions">Flèches ou ZQSD · Espace pour la pause</p><div class="dpad" aria-label="Commandes tactiles"><button class="up" @click="direct('up')" aria-label="Aller en haut"><ArrowUp/></button><button class="left" @click="direct('left')" aria-label="Aller à gauche"><ArrowLeft/></button><button class="down" @click="direct('down')" aria-label="Aller en bas"><ArrowDown/></button><button class="right" @click="direct('right')" aria-label="Aller à droite"><ArrowRight/></button></div><span class="sr-only" role="status">{{ caption }}. Score : {{ state.score }}</span></div></template>
<style scoped>
.snake-score{font-size:14px;margin-right:auto;color:#b5c7b9}.snake-score strong{font:30px var(--mono);color:var(--accent);margin-left:14px}.settings button{display:flex;gap:9px;align-items:center}.snake-board{max-width:500px;margin:0 auto;position:relative;background:#17251c;border:1px solid #546f5b;aspect-ratio:1;touch-action:none}.snake-board>svg{width:100%;height:100%;display:block}.snake-overlay{position:absolute;inset:0;background:#101f17cc;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:18px}.snake-overlay strong{font:36px var(--display)}.snake-overlay p{margin:0}.snake-overlay button{display:flex;align-items:center;gap:10px}.snake-instructions{text-align:center;font-size:13px}.dpad{display:grid;grid-template-columns:repeat(3,48px);grid-template-rows:repeat(2,44px);gap:6px;justify-content:center}.dpad button{display:grid;place-items:center;padding:8px;touch-action:manipulation}.up{grid-column:2}.left{grid-row:2;grid-column:1}.down{grid-row:2;grid-column:2}.right{grid-row:2;grid-column:3}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}
</style>
